s =set()
n = input("Enter a number1: ")
s.add(int(n))
n = input("Enter a number2: ")
s.add(int(n))
n = input("Enter a number3: ")
s.add(int(n))
n = input("Enter a number4: ")
s.add(int(n))
n = input("Enter a number5: ")
s.add(int(n))
n = input("Enter a number6: ")
s.add(int(n))
n = input("Enter a number7: ")
s.add(int(n))
n = input("Enter a number8: ")
s.add(int(n))
n = input("Enter a number9: ")
s.add(int(n))
n = input("Enter a number10: ")
s.add(int(n))
n = input("Enter a number11: ")
s.add(int(n))
n = input("Enter a number12: ")
s.add(int(n))
n = input("Enter a number13: ")
s.add(int(n))
n = input("Enter a number14: ")
s.add(int(n))
print(s)
